=== ganeshgore/myremolab/server/src/voodoo/gen/loader/xsd/machine_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified"
	targetNamespace="http://www.weblab.deusto.es/configuration"
	xmlns:tns="http://www.weblab.deusto.es/configuration"
	>
	<xs:element name="instances">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="runner" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="xs:anyType">
								<xs:attribute name="file" use="required" type="xs:string"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="configuration" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="xs:anyType">
								<xs:attribute name="file" use="required" type="xs:string"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="instance" maxOccurs="unbounded" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="([a-zA-Z0-9_-])+"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ganeshgore/myremolab/server/launch/sample_balanced2_concurrent_experiments/main_machine/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<instances
	xmlns="http://www.weblab.deusto.es/configuration" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="machine_configuration.xsd"
>
    <runner file="launch_sample_balanced2_concurrent_experiments_machine.py"/>
	<configuration file="machine_config.py" />

	<instance>main_instance1</instance>
	<instance>main_instance2</instance>
	<instance>main_instance3</instance>
	<instance>lab_and_experiment1</instance>
	<instance>lab_and_experiment2</instance>
</instances>
